import type { Metadata } from "next";
import "./globals.css";
import SecondaryHeader from "@/components/layouts/SecondaryHeader";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import SecondaryFooter from "@/components/layouts/SecondaryFooter";
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
  title: "Marketplace-Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <Toaster />
        <SecondaryHeader />
        <Header />
        {children}
        <Footer />
        <SecondaryFooter />
      </body>
    </html>
  );
}
